# Hooks
hooks:
  hologram: "DecentHolograms" # Possible values: DecentHolograms, none
  economy: "Vault" # Possible values: Vault, none (I have no idea how you would give money if it is none though)
  bank: "SuperiorSkyBlock" # Possible values: SuperiorSkyBlock, none
  stacker: "WildStacker" # Possible values: WildStacker, RoseStacker, none
  price: "ShopGuiPlus" # Possible values: ShopGuiPlus, EssentialsX, Local

# Whether to allow bStats monitoring for this plugin.
allow-bStats: false

# Whether to check for updates
check-updates: false

# Allow debug
debug: false

# Do not change! This is for internal use only.
config-version: 1