hooks:
  hologram: "DecentHolograms" # Possible values: DecentHolograms, none
  economy: "Vault" # Possible values: Vault, none
  bank: "" # Possible values: SuperiorSkyBlock, none
  stacker: "WildStacker" # Possible values: WildStacker, RoseStacker, none
  price: "ShopGuiPlus" # Possible values: ShopGuiPlus, EssentialsX, Local

allow-bStats: false # Whether to allow bStats monitoring for this plugin.

check-updates: false # Whether to check for updates

config-version: 1 # Do not change! This is for internal use only.