# Hooks
hooks:
  hologram: "DecentHolograms" # Possible values: DecentHolograms, none
  economy: "Vault" # Possible values: Vault, none
  bank: "SuperiorSkyBlock" # Possible values: SuperiorSkyBlock, none
  stacker: "WildStacker" # Possible values: WildStacker, RoseStacker, none
  price: "ShopGuiPlus" # Possible values: ShopGuiPlus, EssentialsX, Local

# Whether to allow bStats monitoring for this plugin.
allow-bStats: false

# Whether to check for updates
check-updates: false

storage:
  type: local # Available options: local, MySQL, MariaDB,
  address: ""
  password: ""
  username: ""
  database: ""

# Allow debug
debug: false

# Do not change! This is for internal use only.
config-version: 1